name: Code quailty check

on:
  workflow_call:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "make lint"
  test:
    name: Unittest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - run: echo "make test"
