name: Deploy to EC2

on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string

jobs:
  deploy:
    name: deploy ${{ inputs.site }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ inputs.site }}
