name: Release Flow

on:
  push:
    tags:
      - '*'

jobs:
  check:
    uses: ./.github/workflows/check.yml
  pack:
    needs: check
    uses: ./.github/workflows/pack.yml
    with:
      image_tag: ${{github.ref_name}}
  dev:
    needs: pack
    uses: ./.github/workflows/deploy.yml
    with:
      site: dev
  stg:
    needs: dev 
    uses: ./.github/workflows/deploy.yml
    with:
      site: stg
  prod:
    needs: stg
    uses: ./.github/workflows/deploy.yml
    with:
      site: prod
