name: Trunk Flow

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yml
  pack:
    needs: check
    uses: ./.github/workflows/pack.yml
    with:
      image_tag: latest
  dev:
    needs: pack
    uses: ./.github/workflows/deploy.yml
    with:
      site: dev
