name: Trunk

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check_subworkflow.yml
  pack:
    needs: check
    uses: ./.github/workflows/pack_subworkflow.yml
    with:
      image_tag: latest
  dev:
    needs: pack
    uses: ./.github/workflows/deploy_subworkflow.yml
    with:
      environment: ${{ github.job }}
      site: dev
